### ISSUE TITLE
Need explanation of when values are stored in trace, and justification for policy

### ISSUE THREAD

**Issue by jar600** [probcomp/metaprob-clojure#42]
For `(block  1 2)` there is no output trace.

If `(define f (gen [x y] 7))`, then for `(f 1 2)` there is no output trace.

For `(+ 1 2)` there is an output trace that tells you that a function called `+` returned the value 3; but there are no subtraces for `1` or `2`.

For `(+ (uniform 0 1) 2)`, the trace says `uniform` returned whatever (say u), and `+` returned u+2. This means that in MH both of these calls are possible modulation points - meaning that we might have `uniform` returning u but `(+ (uniform 0 1) 2)` return v+2 where v not= u.  This seems weird: the program is explicitly specifying a constraint (the value of the outer expression is 2 more than the value of the inner expression), but the program execution is failing to obey it.

It would not be too hard to document the rule - which is pretty simple, only the values returned by primitive procedure calls get recorded (also `inf` procedures can do anything they like including record a value) - but an explanation of what the interpreter does is not going to be very satisfying without some rationale for the policy. I don't understand that rationale.

**Comment by alex-lew** [comment]
I've been thinking about this, too. If we trace the results of primitive function calls like `(+ 2 4)`, we give those computations addresses, which opens them up to intervention/target trace constraints. So we also need an answer to the question of what it means, e.g., to constrain `(+ 2 4)` with a target trace of `{:value 10}`.   

My current thinking (which, as I'm a newbie, shouldn't necessarily hold any weight!) is that it makes the most sense _not_ to record the results of deterministic foreign procedure calls at all; a value goes into a trace only if an `inf` procedure (a 'custom tracer', using the old Metaprob vocabulary) puts it there. I'll paste below the (somewhat wordy...) notes I've been keeping on this:


#### 1. What do the "output traces" Metaprob produces mean?

Every Metaprob procedure implicitly defines a family of distributions over output traces. (A “family,” because applying the procedure to different inputs, or constrained by different intervention or target traces, gives samples from different trace distributions.)

Metaprob programmers can in theory represent any computable (family of) distributions over traces as a procedure, by annotating it with a “custom tracer” (in the current implementation, using `inf`). But we generally assume that output traces can be understood, at least informally, as recording a series of random choices made during a program’s execution. (At what resolution these choices are recorded, and by what scheme they are named, can vary from procedure to procedure.) 

In particular, inference metaprograms (e.g., the single-site Metropolis-Hastings transition operator) seem to me to rely on the validity of viewing traces this way.

#### 2. What does this mean for deterministic procedures?

In light of this, how should Metaprob’s default tracing interpreter handle deterministic procedure calls, like `(+ 1 2)`? I see a couple reasonable options:

1. (**Don't trace anything**) If traces record only random choices, and our procedure is deterministic, perhaps the resulting trace should be empty.
2. (**Trace the return value**) A deterministic computation can be viewed as a "random choice" where 100% of the probability mass falls on one value. Tracing the application of a primitive deterministic procedure `f` to input `x` would then produce the trace `{:value o}`, where `o` is `(f x)`. By tracing the return value, we name it: it now has an address, and can be intervened upon or constrained with a target trace.

The current Metaprob implementation follows option (2), with the following caveats:

* (**Only _foreign_ deterministic procedures are traced**) Pure Metaprob procedures, like `(gen [b] (if b "it was true" "it was false"))`, produce the empty trace. Only calls to foreign Clojure procedures are traced.
* (**Strange things happen when a target trace is provided**) If we try to run, e.g., `(+ 3 4)` with a target trace of `{:value 8}`, we receive an output of 7, a trace of `{:value 8}`, and a score of `0`. I'm not sure what to make of this; it seems to me that we should either 
    * fully embrace the probabilistic semantics, returning an output of 8 and a score of `-Inf` to indicate that our proposed trace `{:value 8}` has probability 0 under the prior, or 

    * completely ignore the target trace, and return `{:value 7}` as the output trace.

#### 3. Consequences for inference.

To help choose between the above options, we can look at the consequences of each for inference. As a running example, consider the following Metaprob procedure, `noisy_flip_and_add`, which chooses two random bits (0 or 1), and returns a noisy observation of their sum:

```clojure
(define noisy-flip-and-add
  (gen []
    (define a (if (flip 0.5) 1 0))
    (define b (if (flip 0.5) 1 0))
    (define c (+ a b))
    (gaussian c 0.5)))
```

*Option 1: Deterministic procedures leave no trace.*
If deterministic procedures like `+` do not trace their results, `noisy-flip-and-add` has only three traced addresses, for the three random choices it makes (flip, flip, and gaussian). All of our inference metaprograms work just fine.

*Option 2: Deterministic procedures trace their output values, but deterministic addresses specified in target traces are completely ignored.*
In this option, `noisy-flip-and-add` generates traces with values at four addresses: the three random choices, and `+`. Because `+` is traced, the Metropolis-Hastings transition operator may sometimes try to propose to the `+` operation. This is harmless, but does mean that about 1/4 of the MH steps we take will be wasted. In a program with more complex deterministic logic, the slowdown could be much worse: imagine, e.g., a program with 5 random choices and 95 deterministic computations. Because this distinction is invisible to the MH transition operator metaprogram, we have no choice but to blindly choose an address and propose to it.

*Option 3: Deterministic procedures trace their output values, and do not ignore target traces.*
Here, if a target trace constrains the result of `+` to be something other than the actual sum of its arguments, the interpreter would return a trace consistent with the target, but give a score of `-Inf`.

Choosing this option has more serious consequences for inference. Imagine we are doing MH inference on `noisy-flip-and-add` to sample from the posterior given that the Gaussian draw is 1. Suppose that our initial trace is `(a=true, b=false, c=1, out=1)`. 

*Any* single-site MH proposal that changes this trace will surely be rejected. For example, suppose we want to flip `a` to `false`. The resulting trace `(a=false, b=false, c=1, out=1)` will have a score of `-Inf`, because it is impossible for `c` to be 1 when `a` and `b` are both false. 

Because of this, we will never reach the other mode of the posterior, `(a=false, b=true, c=1, out=1)`, or  the less plausible (but still possible!) states (like `(a=false, b=false, c=0, out=1)`).

#### 4. My current thinking

At the moment, I think it makes the most sense if only random choices are recorded (option 1). Options 2 and 3 could still be "opted into" with user-defined `inf` procedures:

* A procedure `(traced v)` could have a custom tracer that produces `{:value v}` as an output trace, no matter what (i.e., even if there is a target trace present). This recreates the semantics of option 2.

* A procedure `(dirac-delta v)` could have the probabilistic semantics of randomly drawing from a distribution with mass only at a single point. If constrained with a target trace, it would produce the appropriate score (either 0 or -Inf). This recreates the semantics of option 3.

At first glance, it may seem undesirable to give up the deterministic trace info, which might be useful for other applications — like autodiff. But autodiff requires more than a trace of an output value; we would not use the tracing interpreter for autodiff at all, but rather a special “autodiff interpreter” that recorded both return values and derivatives into an auxiliary data structure.

**Comment by jar398** [comment]
#43 advances this issue considerably.

**Comment by jar398** [comment]
In fact I think #43 lets us close this issue. I will do so, but if @vkmvkmvkmvkm or @alex-lew would like to keep it open, they can just re-open it.
